// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRzfk8_x88U5vzLUKW3OmrQBNUTFeh2Go',
    appId: '1:1046888385454:web:846caed52731b790de163f',
    messagingSenderId: '1046888385454',
    projectId: 'crud-flutter-38eca',
    authDomain: 'crud-flutter-38eca.firebaseapp.com',
    storageBucket: 'crud-flutter-38eca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPIBJhK0ySYc1kHDzmtUVPYHTMae4kIhQ',
    appId: '1:1046888385454:android:72de25c2b811928cde163f',
    messagingSenderId: '1046888385454',
    projectId: 'crud-flutter-38eca',
    storageBucket: 'crud-flutter-38eca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf0tK5DlwYDxdoAHg0PhR_Ebp_bLMP0tg',
    appId: '1:1046888385454:ios:6185d82f1f74d123de163f',
    messagingSenderId: '1046888385454',
    projectId: 'crud-flutter-38eca',
    storageBucket: 'crud-flutter-38eca.appspot.com',
    iosBundleId: 'com.victor.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf0tK5DlwYDxdoAHg0PhR_Ebp_bLMP0tg',
    appId: '1:1046888385454:ios:6185d82f1f74d123de163f',
    messagingSenderId: '1046888385454',
    projectId: 'crud-flutter-38eca',
    storageBucket: 'crud-flutter-38eca.appspot.com',
    iosBundleId: 'com.victor.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRzfk8_x88U5vzLUKW3OmrQBNUTFeh2Go',
    appId: '1:1046888385454:web:2fdd9d209aae89dade163f',
    messagingSenderId: '1046888385454',
    projectId: 'crud-flutter-38eca',
    authDomain: 'crud-flutter-38eca.firebaseapp.com',
    storageBucket: 'crud-flutter-38eca.appspot.com',
  );
}
